export const games = [
  {
    title: "ToTheMoon Lottery",
    description: "Winner takes all style lottery",
    path: "/lottery",
    linkText: "Try now",
  },
  {
    title: "Neptune Lottery",
    description: "Winner takes all style lottery",
    path: "/lottery",
    linkText: "Try now",
  },
  {
    title: "ToTheMoon Lottery",
    description: "Winner takes all style lottery",
    path: "/lottery",
    linkText: "Try now",
  },
  {
    title: "Neptune Lottery",
    description: "Winner takes all style lottery",
    path: "/lottery",
    linkText: "Try now",
  },
  {
    title: "ToTheMoon Lottery",
    description: "Winner takes all style lottery",
    path: "/lottery",
    linkText: "Try now",
  },
  {
    title: "Neptune Lottery",
    description: "Winner takes all style lottery",
    path: "/lottery",
    linkText: "Try now",
  },
  {
    title: "ToTheMoon Lottery",
    description: "Winner takes all style lottery",
    path: "/lottery",
    linkText: "Try now",
  },
  {
    title: "Neptune Lottery",
    description: "Winner takes all style lottery",
    path: "/lottery",
    linkText: "Try now",
  },
  {
    title: "ToTheMoon Lottery",
    description: "Winner takes all style lottery",
    path: "/lottery",
    linkText: "Try now",
  },
  {
    title: "Neptune Lottery",
    description: "Winner takes all style lottery",
    path: "/lottery",
    linkText: "Try now",
  },
  {
    title: "ToTheMoon Lottery",
    description: "Winner takes all style lottery",
    path: "/lottery",
    linkText: "Try now",
  },
  {
    title: "Neptune Lottery",
    description: "Winner takes all style lottery",
    path: "/lottery",
    linkText: "Try now",
  },
  {
    title: "ToTheMoon Lottery",
    description: "Winner takes all style lottery",
    path: "/lottery",
    linkText: "Try now",
  },
  {
    title: "Neptune Lottery",
    description: "Winner takes all style lottery",
    path: "/lottery",
    linkText: "Try now",
  },
];
