# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish-site:
    name: Publish Website on IPFS
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run build --if-present
    - name: Upload to IPFS
      uses: aquiladev/ipfs-action@v0.1.5
      with:
        path: public
        service: pinata
        pinataKey: ${{ secrets.PINATA_API_KEY }}
        pinataSecret: ${{ secrets.PINATA_SECRET_API_KEY }}
        pinataPinName: cosmic.bet website